Updated to use guard file and defaults

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,23 +1,15 @@
 #!/bin/bash
 
-SCRIPT_ABS_LOC="$(readlink -f $0)"
-SCRIPT_LOC="$(dirname ${SCRIPT_ABS_LOC})"
+DEFAULTS="${DEFAULTS:=~/default/dotfiles}"
 
-if [[ -e "$2" ]] ; then
-  GIT_DIR="$(dirname $2)/.git"
-  GIT_WORK_TREE="$(dirname $GIT_DIR)"
-elif [[ "$(basename $SCRIPT_LOC)" == "hooks" ]] ; then
-  GIT_DIR="$(dirname $SCRIPT_LOC)"
-  GIT_WORK_TREE="$(dirname $GIT_DIR)"
-elif [[ "$(basename $SCRIPT_LOC)" == "lib" ]] ; then
-  GIT_DIR="$(dirname $SCRIPT_LOC)/.git"
-  GIT_WORK_TREE="$(dirname $GIT_DIR)"
-else
-  # Unknown Script Location
-  exit 1
-fi
+(( $# >= 1 )) && USER_HOME=${1%/}
+(( $# >= 2 )) && DOTFILES_SRC=${2%/}
+(( $# >= 3 )) && DOTFILES_BKUP=${3%/}
 
-. "${GIT_WORK_TREE}/lib/update_home" "$@"
+[[ -e "${DEFAULTS}" ]] && . "${DEFAULTS}"
+
+[[ -e "${DOTFILES_LOC}/lib/command_setup" ]] && . "${DOTFILES_LOC}/lib/command_setup"
+[[ -e "${DOTFILES_LOC}/lib/update_home" ]] && . "${DOTFILES_LOC}/lib/update_home" || echo "Cannot find helper script aborting ..." && exit 1
 
 install_dotfiles
 
@@ -26,5 +18,5 @@ l_result=$(confirm_move ${l_question})
 if $l_result ; then
   echo ""
   echo ""
-  lnk "Installing GIT Post Merge Hook" "${GIT_WORK_TREE}/lib/post-merge.git_hook" "${GIT_DIR}/hooks/post-merge"
+  lnk "Installing GIT Post Merge Hook" "${DOTFILES_GIT_WORK_TREE}/lib/post-merge.git_hook" "${DOTFILES_GIT_DIR}/hooks/post-merge"
 fi
